### ISSUE TITLE
Issue: Safari iOS cache management fails

### ISSUE THREAD

**Issue by krusty-is-cool** [krusty-is-cool/Covid-Dashboard#10]
- ~New service workers are not token into account: user has to manually delete the website data in the parameters of Safari~,
- After a reasonable period of time, when user hits "refresh" button, the app fails to load the updated data. The service worker seems not to be used by the navigator which may use its own caching system. See screenshot below. The user has to force close the app to reload data. 

![image](https://user-images.githubusercontent.com/47926111/91612723-4de18d80-e97e-11ea-9628-8878204ad3fc.png)

**Comment by krusty-is-cool** [comment]
For an unkown reason, the service worker updates as it should on iOS 13.7. 
I can't figure out what has changed, but for the refresh function after a while is still not working. So, the cache is not served through the service worker.
I keep the issue opened.

**Comment by raymas** [comment]
Do you have any updates on this ?
Which safari versions are affected ?

**Comment by krusty-is-cool** [comment]
On iOS 14.0.1, the page reload works fine.
That was not the case on iOS 13.7.

On iOS 13.5.1 thaugh, the automatic cache update doesn't work. The user must delete manually the data of the site in safari's settings.
I can't check at the moment if the problem persists on iOS 14.0.1 but I will update this issue as soon as I know.

**Comment by krusty-is-cool** [comment]
## Current state of issue
On iOS 14.2, cache does not update when the app is installed on the launch screen. **However**, in Safari, the behaviour seems to be fine. Does iOS manage cache differently for Web Apps ?

## Workaround
Uninstall app and re-install it via Safari

**Comment by krusty-is-cool** [comment]
## Closing the issue
Branch merge #15 (coviddashappv2) solved the problem!
When an update is triggered on the back-end side, the cache is renewed after closing the app:

1. User opens standalone app
2. No change can be seen
3. User closes the app and comes back to it later
4. Changes are taken into account

Conclusion: the new service worker (sw.js) alongside the new back-end (private repo) is effective 😃
